### ISSUE TITLE
iolets are hidden

### ISSUE THREAD

**Issue by tomara-x** [porres/pd-knob#22]
that was confusing!

![Screenshot_2023-04-15_11-46-04](https://user-images.githubusercontent.com/86204514/232206408-2d081c03-af71-4e5f-a0b2-2a7ad4a4e00a.png)

and in run mode you get ghost connections because the border is hidden. i feel like with the border is better looking (kinda like [circle])
![Screenshot_2023-04-15_11-45-42](https://user-images.githubusercontent.com/86204514/232206511-bb15c7b0-27bf-41de-9a70-b32dc7dfeb62.png)

**Comment by porres** [comment]
not sure what this is about but I guess it's a known issue regarding how they get hidden because of a properties bug that I'm waiting for help from @timothyschoen to work on?

The thing is, like the help states, these get hidden when in run mode and also if you have send/receive names. I actually got this idea from MAX, I think i/olets look bad on a patch in run mode and I always find me giving them bogus dummy names in iemguis just so they disappear. Not sure how it all works in plugdata, but it should be the same. 

This is not something particular to knob, objects in Cyclone do that and it is also the standard for ELSE, for example, with [note].

And I also like the option to hide the outline and only show it with the inlet in edit mode. This is exactly the same as with [note], and with MAX's [comment]... but if you want, you can set it to always show the outline with the 'outline' message (not yet implemented in the properties, which is something I'll ask for help later).

Anyway, this seems like either a known bug or an intended feature so I'm closing it
