### ISSUE TITLE
ticks are not a reliable way to see the range

### ISSUE THREAD

**Issue by tomara-x** [porres/pd-knob#23]
they're difficult to see, and sometimes misleading

https://user-images.githubusercontent.com/86204514/232208155-55212cb8-06fe-495e-891e-f8b99df82a49.mp4

**Comment by tomara-x** [comment]
and if you have the arc hidden, then you have no way of looking at it and knowing how far that range is (146 and 236 in those in the picture)
![Screenshot_2023-04-15_12-32-38](https://user-images.githubusercontent.com/86204514/232208717-969edf0b-1438-4d49-ba27-6c4cce7ddc6e.png)

**Comment by porres** [comment]
I guess there might be cases where this happens but they also seem to come up in like weird edge and unorthodox cases... to be honest, that doesn't bother me, if taking into account this context, and also if we add to the context some to value simplicity, not only as a design principle, but also because working with tcl/tk is a nightmare and hard (at least for me) and rather limited. One way or another, maybe this issue should be rewritten to something else, like proposing a better way to always show the range - and then a clear proposal could be made (hopefully not adding too much complexity)...

**Comment by tomara-x** [comment]
i mean you did a nicer design in the video you showed in the discord which i think fixes this

**Comment by porres** [comment]
sure, I havent included here yet so this is why i didn't close it or continued the discussion
